version: '3'
services:
  web:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      ports:
          - "8080:80"
      depends_on:
          - php
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app/code:/var/www/html
  php:
      build:
        context: .
        dockerfile: ./app/Dockerfile
      volumes:
        - ./app/code:/var/www/html
  db:
      build:
        context: .
        dockerfile: ./db/Dockerfile
      ports:
          - "3306:3306"
